# frozen_string_literal: true

require 'factory_bot_rails'

namespace :nba do
  task setup: :environment do
    raise 'This task can not be run in production mode' if Rails.env.production?

    Rake::Task['db:drop'].invoke
    Rake::Task['db:setup'].invoke

    include FactoryBot::Syntax::Methods

    setup_nba_teams
    setup_nba_game_results
  end

  def setup_nba_teams
    create(:nba_team, name: 'Boston Celtics', key: 'BOS', icon_url: 'https://stats.nba.com/media/img/teams/logos/BOS_logo.svg')
    create(:nba_team, name: 'Brooklyn Nets', key: 'BKN', icon_url: 'https://stats.nba.com/media/img/teams/logos/BKN_logo.svg')
    create(:nba_team, name: 'New York Knicks', key: 'NYK', icon_url: 'https://stats.nba.com/media/img/teams/logos/NYK_logo.svg')
    create(:nba_team, name: 'Philadelphia 76ers', key: 'PHI', icon_url: 'https://stats.nba.com/media/img/teams/logos/PHI_logo.svg')
    create(:nba_team, name: 'Toronto Raptors', key: 'TOR', icon_url: 'https://stats.nba.com/media/img/teams/logos/TOR_logo.svg')
    create(:nba_team, name: 'Chicago Bulls', key: 'CHI', icon_url: 'https://stats.nba.com/media/img/teams/logos/CHI_logo.svg')
    create(:nba_team, name: 'Cleveland Cavaliers', key: 'CLE', icon_url: 'https://stats.nba.com/media/img/teams/logos/CLE_logo.svg')
    create(:nba_team, name: 'Detroit Pistons', key: 'DET', icon_url: 'https://stats.nba.com/media/img/teams/logos/DET_logo.svg')
    create(:nba_team, name: 'Indiana Pacers', key: 'IND', icon_url: 'https://stats.nba.com/media/img/teams/logos/IND_logo.svg')
    create(:nba_team, name: 'Milwaukee Bucks', key: 'MIL', icon_url: 'https://stats.nba.com/media/img/teams/logos/MIL_logo.svg')
    create(:nba_team, name: 'Atlanta Hawks', key: 'ATL', icon_url: 'https://stats.nba.com/media/img/teams/logos/ATL_logo.svg')
    create(:nba_team, name: 'Charlotte Hornets', key: 'CHA', icon_url: 'https://stats.nba.com/media/img/teams/logos/CHA_logo.svg')
    create(:nba_team, name: 'Miami Heat', key: 'MIA', icon_url: 'https://stats.nba.com/media/img/teams/logos/MIA_logo.svg')
    create(:nba_team, name: 'Orlando Magic', key: 'ORL', icon_url: 'https://stats.nba.com/media/img/teams/logos/ORL_logo.svg')
    create(:nba_team, name: 'Washington Wizards', key: 'WAS', icon_url: 'https://stats.nba.com/media/img/teams/logos/WAS_logo.svg')
    create(:nba_team, name: 'Denver Nuggets', key: 'DEN', icon_url: 'https://stats.nba.com/media/img/teams/logos/DEN_logo.svg')
    create(:nba_team, name: 'Minnesota Timberwolves', key: 'MIN', icon_url: 'https://stats.nba.com/media/img/teams/logos/MIN_logo.svg')
    create(:nba_team, name: 'Oklahoma City Thunder', key: 'OKC', icon_url: 'https://stats.nba.com/media/img/teams/logos/OKC_logo.svg')
    create(:nba_team, name: 'Portland Trail Blazers', key: 'POR', icon_url: 'https://stats.nba.com/media/img/teams/logos/POR_logo.svg')
    create(:nba_team, name: 'Utah Jazz', key: 'UTA', icon_url: 'https://stats.nba.com/media/img/teams/logos/UTA_logo.svg')
    create(:nba_team, name: 'Golden State Warriors', key: 'GSW', icon_url: 'https://stats.nba.com/media/img/teams/logos/GSW_logo.svg')
    create(:nba_team, name: 'LA Clippers', key: 'LAC', icon_url: 'https://stats.nba.com/media/img/teams/logos/LAC_logo.svg')
    create(:nba_team, name: 'Los Angeles Lakers', key: 'LAL', icon_url: 'https://stats.nba.com/media/img/teams/logos/LAL_logo.svg')
    create(:nba_team, name: 'Phoenix Suns', key: 'PHX', icon_url: 'https://stats.nba.com/media/img/teams/logos/PHX_logo.svg')
    create(:nba_team, name: 'Sacramento Kings', key: 'SAC', icon_url: 'https://stats.nba.com/media/img/teams/logos/SAC_logo.svg')
    create(:nba_team, name: 'Dallas Mavericks', key: 'DAL', icon_url: 'https://stats.nba.com/media/img/teams/logos/DAL_logo.svg')
    create(:nba_team, name: 'Houston Rockets', key: 'HOU', icon_url: 'https://stats.nba.com/media/img/teams/logos/HOU_logo.svg')
    create(:nba_team, name: 'Memphis Grizzlies', key: 'MEM', icon_url: 'https://stats.nba.com/media/img/teams/logos/MEM_logo.svg')
    create(:nba_team, name: 'New Orleans Pelicans', key: 'NOP', icon_url: 'https://stats.nba.com/media/img/teams/logos/NOP_logo.svg')
    create(:nba_team, name: 'San Antonio Spurs', key: 'SAS', icon_url: 'https://stats.nba.com/media/img/teams/logos/SAS_logo.svg')
  end

  def setup_nba_game_results
    create_nba_game_result(team_a_name: 'Philadelphia 76ers', score_a: 87, team_b_name: 'Boston Celtics', score_b: 105)
    create_nba_game_result(team_a_name: 'Oklahoma City Thunder', score_a: 100, team_b_name: 'Golden State Warriors', score_b: 108)
    create_nba_game_result(team_a_name: 'Milwaukee Bucks', score_a: 113, team_b_name: 'Charlotte Hornets', score_b: 112)
    create_nba_game_result(team_a_name: 'Brooklyn Nets', score_a: 100, team_b_name: 'Detroit Pistons', score_b: 103)
    create_nba_game_result(team_a_name: 'Memphis Grizzlies', score_a: 83, team_b_name: 'Indiana Pacers', score_b: 111)
    create_nba_game_result(team_a_name: 'Miami Heat', score_a: 101, team_b_name: 'Orlando Magic', score_b: 104)
    create_nba_game_result(team_a_name: 'Atlanta Hawks', score_a: 107, team_b_name: 'New York Knicks', score_b: 126)
    create_nba_game_result(team_a_name: 'Cleveland Cavaliers', score_a: 104, team_b_name: 'Toronto Raptors', score_b: 116)
    create_nba_game_result(team_a_name: 'New Orleans Pelicans', score_a: 131, team_b_name: 'Houston Rockets', score_b: 112)
    create_nba_game_result(team_a_name: 'Minnesota Timberwolves', score_a: 108, team_b_name: 'San Antonio Spurs', score_b: 112)
    create_nba_game_result(team_a_name: 'Utah Jazz', score_a: 123, team_b_name: 'Sacramento Kings', score_b: 117)
    create_nba_game_result(team_a_name: 'Denver Nuggets', score_a: 107, team_b_name: 'Los Angeles Clippers', score_b: 98)
    create_nba_game_result(team_a_name: 'Dallas Mavericks', score_a: 100, team_b_name: 'Phoenix Suns', score_b: 121)
    create_nba_game_result(team_a_name: 'Chicago Bulls', score_a: 108, team_b_name: 'Philadelphia 76ers', score_b: 127)
    create_nba_game_result(team_a_name: 'Miami Heat', score_a: 113, team_b_name: 'Washington Wizards', score_b: 112)
    create_nba_game_result(team_a_name: 'Los Angeles Lakers', score_a: 119, team_b_name: 'Portland Trail Blazers', score_b: 128)
    create_nba_game_result(team_a_name: 'Charlotte Hornets', score_a: 120, team_b_name: 'Orlando Magic', score_b: 88)
    create_nba_game_result(team_a_name: 'New York Knicks', score_a: 105, team_b_name: 'Brooklyn Nets', score_b: 107)
    create_nba_game_result(team_a_name: 'Atlanta Hawks', score_a: 117, team_b_name: 'Memphis Grizzlies', score_b: 131)
    create_nba_game_result(team_a_name: 'Cleveland Cavaliers', score_a: 123, team_b_name: 'Minnesota Timberwolves', score_b: 131)
    create_nba_game_result(team_a_name: 'Sacramento Kings', score_a: 129, team_b_name: 'New Orleans Pelicans', score_b: 149)
    create_nba_game_result(team_a_name: 'Boston Celtics', score_a: 101, team_b_name: 'Toronto Raptors', score_b: 113)
    create_nba_game_result(team_a_name: 'Indiana Pacers', score_a: 101, team_b_name: 'Milwaukee Bucks', score_b: 118)
    create_nba_game_result(team_a_name: 'Oklahoma City Thunder', score_a: 92, team_b_name: 'Los Angeles Clippers', score_b: 108)
    create_nba_game_result(team_a_name: 'Golden State Warriors', score_a: 124, team_b_name: 'Utah Jazz', score_b: 123)
    create_nba_game_result(team_a_name: 'Brooklyn Nets', score_a: 112, team_b_name: 'Indiana Pacers', score_b: 132)
    create_nba_game_result(team_a_name: 'Toronto Raptors', score_a: 117, team_b_name: 'Washington Wizards', score_b: 113)
    create_nba_game_result(team_a_name: 'Boston Celtics', score_a: 103, team_b_name: 'New York Knicks', score_b: 101)
    create_nba_game_result(team_a_name: 'Orlando Magic', score_a: 115, team_b_name: 'Philadelphia 76ers', score_b: 116)
    create_nba_game_result(team_a_name: 'Detroit Pistons', score_a: 118, team_b_name: 'Chicago Bulls', score_b: 116)
    create_nba_game_result(team_a_name: 'Charlotte Hornets', score_a: 113, team_b_name: 'Miami Heat', score_b: 112)
    create_nba_game_result(team_a_name: 'Minnesota Timberwolves', score_a: 136, team_b_name: 'Dallas Mavericks', score_b: 140)
    create_nba_game_result(team_a_name: 'Phoenix Suns', score_a: 91, team_b_name: 'Denver Nuggets', score_b: 119)
    create_nba_game_result(team_a_name: 'San Antonio Spurs', score_a: 108, team_b_name: 'Portland Trail Blazers', score_b: 121)
    create_nba_game_result(team_a_name: 'Houston Rockets', score_a: 124, team_b_name: 'Los Angeles Lakers', score_b: 115)
    create_nba_game_result(team_a_name: 'Atlanta Hawks', score_a: 133, team_b_name: 'Cleveland Cavaliers', score_b: 111)
    create_nba_game_result(team_a_name: 'Sacramento Kings', score_a: 131, team_b_name: 'Oklahoma City Thunder', score_b: 120)
    create_nba_game_result(team_a_name: 'Golden State Warriors', score_a: 98, team_b_name: 'Denver Nuggets', score_b: 100)
    create_nba_game_result(team_a_name: 'Houston Rockets', score_a: 112, team_b_name: 'Los Angeles Clippers', score_b: 115)
    create_nba_game_result(team_a_name: 'Orlando Magic', score_a: 93, team_b_name: 'Boston Celtics', score_b: 90)
    create_nba_game_result(team_a_name: 'Charlotte Hornets', score_a: 106, team_b_name: 'Toronto Raptors', score_b: 127)
    create_nba_game_result(team_a_name: 'New York Knicks', score_a: 113, team_b_name: 'Milwaukee Bucks', score_b: 124)
    create_nba_game_result(team_a_name: 'Indiana Pacers', score_a: 91, team_b_name: 'Minnesota Timberwolves', score_b: 101)
    create_nba_game_result(team_a_name: 'Chicago Bulls', score_a: 109, team_b_name: 'Dallas Mavericks', score_b: 115)
    create_nba_game_result(team_a_name: 'Memphis Grizzlies', score_a: 92, team_b_name: 'Utah Jazz', score_b: 84)
    create_nba_game_result(team_a_name: 'Washington Wizards', score_a: 125, team_b_name: 'Portland Trail Blazers', score_b: 124)
    create_nba_game_result(team_a_name: 'Phoenix Suns', score_a: 103, team_b_name: 'Golden State Warriors', score_b: 123)
    create_nba_game_result(team_a_name: 'San Antonio Spurs', score_a: 143, team_b_name: 'Los Angeles Lakers', score_b: 142)
    create_nba_game_result(team_a_name: 'Philadelphia 76ers', score_a: 132, team_b_name: 'Detroit Pistons', score_b: 133)
    create_nba_game_result(team_a_name: 'Los Angeles Clippers', score_a: 109, team_b_name: 'New Orleans Pelicans', score_b: 116)
    create_nba_game_result(team_a_name: 'Sacramento Kings', score_a: 112, team_b_name: 'Denver Nuggets', score_b: 126)
    create_nba_game_result(team_a_name: 'Dallas Mavericks', score_a: 104, team_b_name: 'Atlanta Hawks', score_b: 111)
    create_nba_game_result(team_a_name: 'Brooklyn Nets', score_a: 102, team_b_name: 'Cleveland Cavaliers', score_b: 86)
    create_nba_game_result(team_a_name: 'New York Knicks', score_a: 87, team_b_name: 'Miami Heat', score_b: 110)
    create_nba_game_result(team_a_name: 'Minnesota Timberwolves', score_a: 105, team_b_name: 'Toronto Raptors', score_b: 112)
    create_nba_game_result(team_a_name: 'Charlotte Hornets', score_a: 110, team_b_name: 'Chicago Bulls', score_b: 112)
    create_nba_game_result(team_a_name: 'Utah Jazz', score_a: 100, team_b_name: 'Houston Rockets', score_b: 89)
    create_nba_game_result(team_a_name: 'Indiana Pacers', score_a: 116, team_b_name: 'San Antonio Spurs', score_b: 96)
    create_nba_game_result(team_a_name: 'Philadelphia 76ers', score_a: 108, team_b_name: 'Milwaukee Bucks', score_b: 123)
    create_nba_game_result(team_a_name: 'Los Angeles Lakers', score_a: 131, team_b_name: 'Phoenix Suns', score_b: 113)
    create_nba_game_result(team_a_name: 'Memphis Grizzlies', score_a: 92, team_b_name: 'Sacramento Kings', score_b: 97)
    create_nba_game_result(team_a_name: 'Washington Wizards', score_a: 122, team_b_name: 'Golden State Warriors', score_b: 144)
    create_nba_game_result(team_a_name: 'Cleveland Cavaliers', score_a: 103, team_b_name: 'Detroit Pistons', score_b: 110)
    create_nba_game_result(team_a_name: 'Portland Trail Blazers', score_a: 128, team_b_name: 'Orlando Magic', score_b: 114)
    create_nba_game_result(team_a_name: 'Boston Celtics', score_a: 101, team_b_name: 'Oklahoma City Thunder', score_b: 95)
    create_nba_game_result(team_a_name: 'Denver Nuggets', score_a: 114, team_b_name: 'Los Angeles Lakers', score_b: 121)
    create_nba_game_result(team_a_name: 'Chicago Bulls', score_a: 106, team_b_name: 'Charlotte Hornets', score_b: 135)
    create_nba_game_result(team_a_name: 'Golden State Warriors', score_a: 128, team_b_name: 'New York Knicks', score_b: 100)
    create_nba_game_result(team_a_name: 'Dallas Mavericks', score_a: 107, team_b_name: 'Toronto Raptors', score_b: 116)
    create_nba_game_result(team_a_name: 'Los Angeles Clippers', score_a: 133, team_b_name: 'Houston Rockets', score_b: 113)
    create_nba_game_result(team_a_name: 'Milwaukee Bucks', score_a: 125, team_b_name: 'Minnesota Timberwolves', score_b: 95)
    create_nba_game_result(team_a_name: 'Brooklyn Nets', score_a: 115, team_b_name: 'New Orleans Pelicans', score_b: 117)
    create_nba_game_result(team_a_name: 'Washington Wizards', score_a: 112, team_b_name: 'Sacramento Kings', score_b: 116)
    create_nba_game_result(team_a_name: 'Boston Celtics', score_a: 109, team_b_name: 'Detroit Pistons', score_b: 89)
    create_nba_game_result(team_a_name: 'Utah Jazz', score_a: 132, team_b_name: 'New Orleans Pelicans', score_b: 111)
    create_nba_game_result(team_a_name: 'Chicago Bulls', score_a: 97, team_b_name: 'Atlanta Hawks', score_b: 85)
    create_nba_game_result(team_a_name: 'Indiana Pacers', score_a: 119, team_b_name: 'Cleveland Cavaliers', score_b: 107)
    create_nba_game_result(team_a_name: 'Charlotte Hornets', score_a: 103, team_b_name: 'Philadelphia 76ers', score_b: 105)
    create_nba_game_result(team_a_name: 'Phoenix Suns', score_a: 96, team_b_name: 'Memphis Grizzlies', score_b: 117)
    create_nba_game_result(team_a_name: 'Portland Trail Blazers', score_a: 111, team_b_name: 'Miami Heat', score_b: 120)
    create_nba_game_result(team_a_name: 'Orlando Magic', score_a: 91, team_b_name: 'Milwaukee Bucks', score_b: 113)
    create_nba_game_result(team_a_name: 'Los Angeles Lakers', score_a: 106, team_b_name: 'San Antonio Spurs', score_b: 110)
    create_nba_game_result(team_a_name: 'Golden State Warriors', score_a: 120, team_b_name: 'Brooklyn Nets', score_b: 114)
    create_nba_game_result(team_a_name: 'Utah Jazz', score_a: 113, team_b_name: 'Dallas Mavericks', score_b: 104)
    create_nba_game_result(team_a_name: 'Phoenix Suns', score_a: 110, team_b_name: 'Oklahoma City Thunder', score_b: 117)
    create_nba_game_result(team_a_name: 'Washington Wizards', score_a: 104, team_b_name: 'Los Angeles Clippers', score_b: 136)
    create_nba_game_result(team_a_name: 'Portland Trail Blazers', score_a: 103, team_b_name: 'Indiana Pacers', score_b: 93)
    create_nba_game_result(team_a_name: 'Atlanta Hawks', score_a: 92, team_b_name: 'Philadelphia 76ers', score_b: 113)
    create_nba_game_result(team_a_name: 'Sacramento Kings', score_a: 123, team_b_name: 'Miami Heat', score_b: 113)
    create_nba_game_result(team_a_name: 'Brooklyn Nets', score_a: 96, team_b_name: 'New York Knicks', score_b: 115)
    create_nba_game_result(team_a_name: 'Golden State Warriors', score_a: 149, team_b_name: 'Chicago Bulls', score_b: 124)
    create_nba_game_result(team_a_name: 'Toronto Raptors', score_a: 109, team_b_name: 'Milwaukee Bucks', score_b: 124)
    create_nba_game_result(team_a_name: 'Los Angeles Lakers', score_a: 120, team_b_name: 'Minnesota Timberwolves', score_b: 124)
    create_nba_game_result(team_a_name: 'Dallas Mavericks', score_a: 108, team_b_name: 'San Antonio Spurs', score_b: 113)
    create_nba_game_result(team_a_name: 'New Orleans Pelicans', score_a: 111, team_b_name: 'Denver Nuggets', score_b: 116)
    create_nba_game_result(team_a_name: 'Miami Heat', score_a: 113, team_b_name: 'Charlotte Hornets', score_b: 125)
    create_nba_game_result(team_a_name: 'Atlanta Hawks', score_a: 114, team_b_name: 'Cleveland Cavaliers', score_b: 136)
    create_nba_game_result(team_a_name: 'Sacramento Kings', score_a: 107, team_b_name: 'Orlando Magic', score_b: 99)
    create_nba_game_result(team_a_name: 'Detroit Pistons', score_a: 105, team_b_name: 'Boston Celtics', score_b: 108)
    create_nba_game_result(team_a_name: 'Philadelphia 76ers', score_a: 112, team_b_name: 'Toronto Raptors', score_b: 129)
    create_nba_game_result(team_a_name: 'Portland Trail Blazers', score_a: 104, team_b_name: 'Houston Rockets', score_b: 85)
    create_nba_game_result(team_a_name: 'Washington Wizards', score_a: 95, team_b_name: 'Memphis Grizzlies', score_b: 107)
    create_nba_game_result(team_a_name: 'Los Angeles Clippers', score_a: 110, team_b_name: 'Oklahoma City Thunder', score_b: 128)
    create_nba_game_result(team_a_name: 'Detroit Pistons', score_a: 119, team_b_name: 'Brooklyn Nets', score_b: 120)
    create_nba_game_result(team_a_name: 'Denver Nuggets', score_a: 108, team_b_name: 'Chicago Bulls', score_b: 107)
    create_nba_game_result(team_a_name: 'Utah Jazz', score_a: 125, team_b_name: 'Minnesota Timberwolves', score_b: 128)
    create_nba_game_result(team_a_name: 'Indiana Pacers', score_a: 107, team_b_name: 'New York Knicks', score_b: 101)
    create_nba_game_result(team_a_name: 'New Orleans Pelicans', score_a: 121, team_b_name: 'Golden State Warriors', score_b: 131)
    create_nba_game_result(team_a_name: 'Dallas Mavericks', score_a: 113, team_b_name: 'Los Angeles Lakers', score_b: 114)
    create_nba_game_result(team_a_name: 'San Antonio Spurs', score_a: 120, team_b_name: 'Phoenix Suns', score_b: 90)
  end

  def create_nba_game_result(team_a_name:, score_a:, team_b_name:, score_b:)
    team_a = NbaTeam.find_by(name: team_a_name)
    puts "Unknow Team name: #{team_a_name}" && return if team_a.nil?
    team_b = NbaTeam.find_by(name: team_b_name)
    puts "Unknow Team name: #{team_b_name}" && return if team_b.nil?

    create(:nba_game_result,
           team_a: team_a,
           score_a: score_a,
           team_b: team_b,
           score_b: score_b)
  end
end
